scribe:
  auth:
    login-url: https://scribe-hub-dev.us.auth0.com
    grant-type: client_credentials
    enable: true
    audience: api.dev.scribesecurity.com
  url: https://airflow.dev.scribesecurity.com
  enable: true
attest:
  cocosign:
    policies:
    - enable: true
      name: marsh-policy
      modules:
      - enable: true
        type: verify-artifact
        name: superset-policy
        input:
          signed: false
          format: attest-cyclonedx-json
          rego:
            path: .valint.rego
            args:
              superset:
                username: CLIENT_ID
                password: CLIENT_SECRET
                licences:
                  max: 500
                cve:
                  max: 3
                unmaintained:
                  max: 2000
                images:
                  max: 20
